/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * API
 * API documentation
 * OpenAPI spec version: 1.0
 */
export type Logout200 = {
  message?: string;
};

export type RefreshToken200 = {
  accessToken?: string;
  message?: string;
};

export type VerifyRegister200 = {
  accessToken?: string;
  message?: string;
  refreshToken?: string;
};

export type VerifyLogin200 = {
  accessToken?: string;
  message?: string;
  refreshToken?: string;
};

export type RegisterUser201 = {
  message?: string;
  registerToken?: string;
  verifyRegisterUrl?: string;
};

export type Login201 = {
  loginToken?: string;
  message?: string;
  verifyLoginUrl?: string;
};

export type DeleteUserById200User = {
  createdAt?: string;
  email?: string;
  fisrtName?: string;
  id?: number;
  imageUrl?: string;
  lastName?: string;
  role?: string;
  updatedAt?: string;
  verified?: boolean;
  whatsappNumber?: string;
};

export type DeleteUserById200 = {
  message?: string;
  user?: DeleteUserById200User;
};

export type UpdateUserById200UpdatedFields = { [key: string]: unknown };

export type UpdateUserById200 = {
  message?: string;
  updatedFields?: UpdateUserById200UpdatedFields;
};

export type FindUserById200 = {
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: number;
  imageUrl?: string;
  lastName?: string;
  role?: string;
  updatedAt?: string;
  verified?: boolean;
  /** @nullable */
  whatsappNumber?: string | null;
};

export type GetUsers200Item = {
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: number;
  imageUrl?: string;
  lastName?: string;
  role?: string;
  updatedAt?: string;
  verified?: boolean;
  whatsappNumber?: string;
};

export type DeleteUser200User = {
  createdAt?: string;
  email?: string;
  fisrtName?: string;
  id?: number;
  imageUrl?: string;
  lastName?: string;
  role?: string;
  updatedAt?: string;
  verified?: boolean;
  whatsappNumber?: string;
};

export type DeleteUser200 = {
  message?: string;
  user?: DeleteUser200User;
};

export type UpdateUser200UpdatedFields = { [key: string]: unknown };

export type UpdateUser200 = {
  message?: string;
  updatedFields?: UpdateUser200UpdatedFields;
};

export type UserDetails200 = {
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  role?: string;
  updatedAt?: string;
  verified?: boolean;
  whatsappNumber?: string;
};

export interface CreateUserDto {
  /** Email do usuário */
  email: string;
  /** Primeiro nome do usuário */
  firstName: string;
  /** Sobrenome do usuário */
  lastName: string;
  /** Número do WhatsApp */
  whatsappNumber?: string;
}

export interface LoginDto {
  /** Email do usuário */
  email: string;
}

export interface UpdateUserDto {
  /** Email do usuário */
  email: string;
  /** Primeiro nome do usuário */
  firstName: string;
  /** Sobrenome do usuário */
  lastName: string;
  /** Número do WhatsApp */
  whatsappNumber?: string;
}

